# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    command: /app/entrypoint.sh
    env_file:
      - .env
    restart: always
    ports:
      - "80:5000"
      - "8080:8080"
    volumes:
      - meli-chatwoot-data:/app

volumes:
  meli-chatwoot-data:
