# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    command: /app/entrypoint.sh
    env_file:
      - .env
    restart: always
    ports:
      - "80:5000"   # Porta para o webhook da aplicação principal
      - "8080:8080" # Porta para o instalador web
    volumes:
      # No EasyPanel, a configuração de volume é feita pela interface gráfica.
      # Esta linha é para referência de desenvolvimento local.
      - meli-chatwoot-data:/app

volumes:
  meli-chatwoot-data:
